server.port: 9090
#server.http2.enabled: true
#server.ssl.key-store: classpath:ds.jks
#server.ssl.key-store-type: pkcs12
#server.ssl.key-store-password: password
#server.ssl.key-password: password
#server.ssl.key-alias: ds